export const WORKER_CONFIG = {
    SUBMITTED_TIMEOUT_SECONDS: 90,
    BACKOFF_SCHEDULE: [10, 30, 60, 120, 300],
    MAX_ATTEMPTS: 5,
    TICK_INTERVAL_MS: 3000,
    JOB_BATCH_SIZE: 5,
    CONCURRENCY: 3,
} as const;
